# Note that any updates to this files will not be applied in CI
# until this file is merged into main. This is due to oddities of the labeller Github Action.
"C:app-wiring":
  # Match all of app folder except wasm sub-folder
  - app/*.go
  - app/keepers/**/*
  - app/params/**/*
  - app/upgrades/**/*
  # Also match any module.go update
  - x/**/module.go
"C:x/bet":
  - x/bet/**/*
"C:x/dvm":
  - x/dvm/**/*
"C:x/mint":
  - x/mint/**/*
"C:x/sportevent":
  - x/sportevent/**/*
"C:x/strategicreserve":
  - x/strategicreserve/**/*
"T:build":
  - Makefile
  - scripts/*
"T:CI":
  - .github/**/*.yml
  - .hadolint.yml
  - .golangci.yml
"C:CLI":
  - x/*/client/**/*
# Add "C:docs" label to documented related files and directories.
"C:docs":
  - docs/*.md
  - docs/**/*.md
  - docs/**/**/*.md
  - README.md
  - x/**/*.md
  - x/**/*/*.md
