name: Deploy Proto & NPM publish

on:
  pull_request:
    types: [opened, edited, synchronize]
env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
  NPM_VERSION: patch


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3.0.0
      with:
        ref: master
        repository: sge-network/sge
        path: sge

    - name: Checkout destination repository
      uses: actions/checkout@v3.0.0
      with:     
        ref: master
        repository: ${{ secrets.ST_REPO }}/sgejs
        path: sgejs
        token: ${{ secrets.ST_TOKEN }}
        
    - name: Copy Proto Files
      run: |
        cp -r sge/proto/sge sgejs/proto
        git -C sgejs add .
        git -C sgejs status
     

    - name: Npm Install
      run: |
        echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > sgejs/.npmrc      
        npm install --prefix sgejs
    
    - name: Move src/codegen and types
      run: |
        mv sgejs/src/codegen ~/
        mv sgejs/types ~/
        
    - name: Npm Run Codegen
      run: |
        npm run codegen --prefix sgejs
        
    - name: Move src/codegen and types
      run: |
        mv codegen sgejs/src/
        mv types sgejs/

    - name: Commit changes
      run: |
        git -C sgejs checkout .      
        git -C sgejs config user.email "action@github.com"
        git -C sgejs config user.name "GitHub Action"
        git -C sgejs commit --allow-empty -am "Proto Deployment [skip ci]"
        
    - name: Determine NPM version
      run: |
        cd sgejs      
        if [[ "${{ github.event.pull_request.title }}" == *"major"* ]]; then
          echo "NPM_VERSION=major" >> $GITHUB_ENV
        elif [[ "${{ github.event.pull_request.title }}" == *"minor"* ]]; then
          echo "NPM_VERSION=minor" >> $GITHUB_ENV
        elif [[ "${{ github.event.pull_request.title }}" == *"patch"* ]]; then
          echo "NPM_VERSION=patch" >> $GITHUB_ENV
        fi
        
    - name: Bump NPM version
      run: |
        cd sgejs          
        git status
        if [ "${{ env.NPM_VERSION }}" == "major" ]; then
          npm version major
        elif [ "${{ env.NPM_VERSION }}" == "minor" ]; then
          npm version minor
        elif [ "${{ env.NPM_VERSION }}" == "patch" ]; then
          npm version patch
        fi
        git status
        
    - name: Push sgejs
      run: git -C sgejs push        
        
    - name: Publish NPM Package
      run: |
        echo "//registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN" > sgejs/.npmrc
        cat sgejs/.npmrc
        cd sgejs
        npm publish --access=restricted --force
